ERROR 2025-02-02 14:13:53,566 views Error log
ERROR 2025-02-02 14:15:36,780 views Error log
ERROR 2025-02-02 14:17:01,986 views Error log
ERROR 2025-02-02 14:17:23,576 views Error log
ERROR 2025-02-03 01:26:25,124 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:26:25,128 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:34:17,481 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:34:17,488 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:34:22,236 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:34:22,242 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:35:30,816 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:35:30,821 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:36:29,927 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:36:29,927 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:36:36,511 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:36:36,511 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:37:43,946 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:37:43,946 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:40:56,921 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:40:56,924 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:04,791 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:04,796 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:11,754 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:11,754 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:11,754 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:11,754 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:14,921 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-03 01:41:14,936 basehttp You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-02-05 22:04:04,423 views Unexpected error in borrowing_student_prebookview: UNIQUE constraint failed: core_borrow_info.borrow_id
Traceback (most recent call last):
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: core_borrow_info.borrow_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\core\views.py", line 1764, in borrowing_student_prebookview
    borrow_entry = borrow_info.objects.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\core\models.py", line 403, in save
    super().save(*args, **kwargs)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: core_borrow_info.borrow_id
ERROR 2025-02-05 22:06:37,125 views Unexpected error in borrowing_student_prebookview: UNIQUE constraint failed: core_borrow_info.borrow_id
Traceback (most recent call last):
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: core_borrow_info.borrow_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\core\views.py", line 1764, in borrowing_student_prebookview
    borrow_entry = borrow_info.objects.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\core\models.py", line 403, in save
    super().save(*args, **kwargs)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\domin\OneDrive\Documents\GitHub\labmas_2\lab_management\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: core_borrow_info.borrow_id
